### ISSUE TITLE
Typo in comment in Figure 4-11

### ISSUE THREAD

**Issue by PiotrFusik** [Apress/data-parallel-CPP#10]
There's a comment:

    // Return the offset of this item (if with_offset == true)

but the template parameter is spelled `WithOffset`.

**Comment by jamesreinders** [comment]
Thank you.  I added it to the book errata, and we'll update when we update the book (hopefully in 2022).

**Comment by mkinsner** [comment]
Source fix in https://github.com/Apress/data-parallel-CPP/pull/101

**Comment by mkinsner** [comment]
SYCL spec fix in https://github.com/KhronosGroup/SYCL-Docs/pull/422

**Comment by mkinsner** [comment]
Thanks for pointing this out!
