### ISSUE TITLE
Reference for collective functions section at end of chapter 9

### ISSUE THREAD

**Issue by firthmj** [Apress/data-parallel-CPP#11]
Hi,

At the end of chapter 9, there is discussion of some collective functions including "broadcast", "any_of"/"all_of", "shuffle"/"shuffle_up"/"shuffle_down" and "shuffle_xor".

None of these seem to come up in a search of the reference linked from Chapter 1 at http://tinyurl.com/dpcppref

Have these methods been moved / removed from the core standard? If not, is there a URL with further details on how these work?

I wasn't able to quite work out exactly what they all do from that section of the book, so was looking for some more description or examples.

**Comment by Pennycook** [comment]
Apologies for the delayed response.  This is one area where the syntax changed fairly significantly when the functionality was added to SYCL 2020.

The syntax described in the book is still supported by the DPC++ compiler.  The documentation for collective functions supported by both work-groups and sub-groups is available [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/GroupAlgorithms/SYCL_INTEL_group_algorithms.asciidoc), and the documentation for collective functions only supported by sub-groups is available [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/SubGroupAlgorithms/SYCL_INTEL_sub_group_algorithms.asciidoc).

The equivalent functionality in the SYCL 2020 specification is documented in [Section 4.17.3, "Group functions"](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:group-functions) and [Section 4.17.4, "Group algorithms library"](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:algorithms).  The constraints for each function describe whether it supports work-groups and sub-groups, or only sub-groups.

A quick rundown of the name changes is below.  The mapping isn't necessarily obvious, but the SYCL 2020 names are intended to be more descriptive of what the functions do:

- `broadcast` => `group_broadcast`
- `any_of` => `joint_any_of` and `any_of_group`
- `shuffle` => `select_from_group`
- `shuffle_up` => `shift_group_right`
- `shuffle_down` => `shift_group_left`
- `shuffle_xor` => `permute_group_by_xor`

**Comment by mkinsner** [comment]
The main branch has been updated with all of the new/standard names.  These will be reflected in the next edition of the book when it comes out.
