### ISSUE TITLE
Build error in Ch18 examples

### ISSUE THREAD

**Issue by JDonner** [Apress/data-parallel-CPP#12]
[CMakeCache.txt](https://github.com/Apress/data-parallel-CPP/files/6362458/CMakeCache.txt)
When I try to build the book's examples from this repo, with Ubuntu 20.04:

```
.../mkoneapi-book-examples/data-parallel-CPP$ mkdir build                                                                                                                                
.../mkoneapi-book-examples/data-parallel-CPP$ cd build                                                                                                                                   
.../data-parallel-CPP/build$ source /opt/intel/oneapi/setvars.sh
:: initializing oneAPI environment ...
   bash: BASH_VERSION = 5.0.17(1)-release
:: compiler -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dpl -- latest
:: tbb -- latest
:: vpl -- latest
:: oneAPI environment initialized ::
.../data-parallel-CPP/build$ cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=../dpcpp_toolchain.cmake ..
-- No build type selected, default to Release
-- The C compiler identification is Clang 12.0.0
-- The CXX compiler identification is Clang 12.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/2021.2.0/linux/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2021.2.0/linux/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /space/mkoneapi-book-examples/data-parallel-CPP/build
build $ cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=../dpcpp_toolchain.cmake ..
build $ ninja

....


[219/250] Building CXX object samples/Ch18_using_libs/CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o
FAILED: samples/Ch18_using_libs/CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o 
/opt/intel/oneapi/compiler/2021.2.0/linux/bin/clang++   -O3 -DNDEBUG -fsycl -fsycl-unnamed-lambda -ferror-limit=1 -Wall -Wpedantic -std=gnu++17 -MD -MT samples/Ch18_using_libs/CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o -MF samples/Ch18_using_libs/CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o.d -o samples/Ch18_using_libs/CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o -c ../samples/Ch18_using_libs/fig_18_15_pstl_usm.cpp
In file included from ../samples/Ch18_using_libs/fig_18_15_pstl_usm.cpp:6:
In file included from /opt/intel/oneapi/dpl/2021.2.0/linux/include/oneapi/dpl/execution:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/execution:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/glue_execution_defs.h:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/algorithm_impl.h:25:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend.h:14:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend_tbb.h:70:10: error: no member named 'task' in namespace 'tbb'
    tbb::task::self().group()->cancel_group_execution();
    ~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.

```

**Comment by Pennycook** [comment]
There is a known incompatibility with the GCC 9 headers.

From https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-library-release-notes.html:

> The use of oneDPL together with the GNU C++ standard library (libstdc++) version 9 or 10 may lead to compilation errors (caused by oneTBB API changes). To overcome these issues, include oneDPL header files before the standard C++ header files, or disable parallel algorithms support in the standard library. For more information, please see Intel® oneAPI Threading Building Blocks (oneTBB) Release Notes.

From https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html:

> An application using Parallel STL algorithms in libstdc++ versions 9 and 10 may fail to compile due to incompatible interface changes between earlier versions of Threading Building Blocks (TBB) and oneAPI Threading Building Blocks (oneTBB). Disable support for Parallel STL algorithms by defining PSTL_USE_PARALLEL_POLICIES (in libstdc++ 9) or _GLIBCXX_USE_TBB_PAR_BACKEND (in libstdc++  10) macro to zero before inclusion of the first standard header file in each translation unit.

Could you please try one of these suggested fixes, and see if they address the issue?

**Comment by JDonner** [comment]
Huh. I don't know how GCC's libstdc++ gets in there, it's driven by Intel's clang++. I don't see my system injecting GCC anywhere. 

`
[ 92%] Building CXX object samples/Ch18_using_libs/CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o
cd /space/mkoneapi-book-examples/data-parallel-CPP/build/samples/Ch18_using_libs && /opt/intel/oneapi/compiler/2021.2.0/linux/bin/clang++   -O3 -DNDEBUG -fsycl -fsycl-unnamed-lambda -ferror-limit=1 -Wall -Wpedantic -std=gnu++17 -o CMakeFiles/fig_18_15_pstl_usm.dir/fig_18_15_pstl_usm.cpp.o -c /space/mkoneapi-book-examples/data-parallel-CPP/samples/Ch18_using_libs/fig_18_15_pstl_usm.cpp
In file included from /space/mkoneapi-book-examples/data-parallel-CPP/samples/Ch18_using_libs/fig_18_15_pstl_usm.cpp:6:
In file included from /opt/intel/oneapi/dpl/2021.2.0/linux/include/oneapi/dpl/execution:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/execution:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/glue_execution_defs.h:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/algorithm_impl.h:25:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend.h:14:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend_tbb.h:70:10: error: no member named 'task' in namespace 'tbb'
    tbb::task::self().group()->cancel_group_execution();
    ~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
`

Also, the included Intel <execution>: /opt/intel/oneapi/dpl/2021.2.0/linux/include/oneapi/dpl/execution
explicitly includes 'the system's' <execution> first, for its own reasons: 

`
#ifndef _ONEDPL_EXECUTION
#define _ONEDPL_EXECUTION

// Workarounds for libstdc++9, libstdc++10 when new TBB version is found in the environment
#if __cplusplus >= 201703L
#    if __has_include(<tbb/version.h>)
#        ifndef PSTL_USE_PARALLEL_POLICIES
#            define PSTL_USE_PARALLEL_POLICIES (_GLIBCXX_RELEASE != 9)
#        endif
#        ifndef _GLIBCXX_USE_TBB_PAR_BACKEND
#            define _GLIBCXX_USE_TBB_PAR_BACKEND (_GLIBCXX_RELEASE > 10)
#        endif
#    endif // __has_include(<tbb/version.h>)

// ATTENTION!!! Include the header from the C++ standard library before the oneDPL config header to see whether the _PSTL_VERSION macro is defined
#    if __has_include(<execution>)
#        include <execution>
#    endif // __has_include(<execution>)
#endif     // __cplusplus >= 201703L

#include "oneapi/dpl/pstl/onedpl_config.h"
#include "oneapi/dpl/pstl/execution_defs.h"

// etc ....
`

I see that clang 12 has an <execution> implementation, is the solution to just point the examples build to the local clang, somehow? I see that the previous oneapi version, 2021.1.2 doesn't have an <execution> header. I need to use the PSTL on Ubuntu, is there a way to proceed? Thanks.

**Comment by akukanov** [comment]
GCC, and its standard library libstdc++, are the default C++ environment on your Ubuntu system. Intel's compiler does not ship its own standard library but uses the one available on the system.

This is the relevant code of the [sample](https://github.com/Apress/data-parallel-CPP/blob/main/samples/Ch18_using_libs/fig_18_15_pstl_usm.cpp):

    #include <CL/sycl.hpp>
    #include <oneapi/dpl/execution>
    #include <oneapi/dpl/algorithm>

The SYCL header is included first, and seemingly it includes some C++ standard library headers internally. When the oneDPL headers are included, libstdc++ is already initialized, so the internal oneDPL workaround for the compatibility issue cannot be applied.

To overcome this, one needs to manually apply the recommendations @Pennycook cited, i.e. either make sure oneDPL headers go first in the code, like this:

    #include <oneapi/dpl/execution>
    #include <oneapi/dpl/algorithm>
    #include <CL/sycl.hpp>

or, if that cannot be done or does not help, explicitly disable the use of TBB headers in libstdc++ by setting the required macro to 0, e.g. as a compiler option `-D PSTL_USE_PARALLEL_POLICIES=0`. Unfortunately, I have very little expertise in Cmake and ninja, so I cannot suggest how to specify an extra compiler option there.

**Comment by mkinsner** [comment]
Closing assuming that resolved by the suggestions above.  Please reopen if still an issue
