### ISSUE TITLE
book's fig_1_3_race example fails if gpu has max_sub_devices=0

### ISSUE THREAD

**Issue by jnorwood** [Apress/data-parallel-CPP#14]
I played around with the race example long enough to figure out it would not fail on my gpu.  I could make a race occur on a cpu_selector device by changing the memcpy kernel to a parallel_for kernel copy and inserting a decrement delay count in its kernel code.   

With my GPU as the default device, no size delay would create the race, so I'm presuming it is because my GPU is only capable of one thread, which I verified by printing partition_max_sub_devices.   

default_selector: Selected device: Intel(R) Iris(TM) Pro Graphics 580 [0x193b]
                  -> Device vendor: Intel(R) Corporation
                  -> Device partition_max_sub_devices: 0

I suggest changing the race example to explicitly use a cpu selector and to insert some delays in the first kernel loop.

**Comment by jamesreinders** [comment]
Thank you.  I've made a note in the 2nd edition about this quirk of race conditions - that they don't always cause a failure. Your example and explanation make sense.
