### ISSUE TITLE
is_host() returns 0 for device selected by host_selector

### ISSUE THREAD

**Issue by jnorwood** [Apress/data-parallel-CPP#15]
I modified example fig_2_7 to display has(aspect) and is_something returns.  I'm puzzled why a device selected by host_selector would return 0 for is_host().

I'm running all these in the docker environment for oneapi and using cmake for the builds on ubuntu 20.04

I'm attaching my modified example code.
[fig_2_7_implicit_default_selector.zip](https://github.com/Apress/data-parallel-CPP/files/6689181/fig_2_7_implicit_default_selector.zip)

**Comment by mkinsner** [comment]
The host device (hence `host_selector`) no longer exists as of SYCL 2020.  CPU devices replace most of the functionality.

I expect that what you observed was a bug or incomplete feature in the implementation.  I'm closing this issue, but please reopen if you believe that this is still exposed in SYCL 2020 and recent compiler builds.
