### ISSUE TITLE
initializing events as non-signaled

### ISSUE THREAD

**Issue by jnorwood** [Apress/data-parallel-CPP#20]
Windows has synchronization events that can be initialized as non-signaled.
See [https://docs.microsoft.com/en-us/windows/win32/sync/using-event-objects](https://docs.microsoft.com/en-us/windows/win32/sync/using-event-objects)

Is there a way to initialize events as non-signaled in sycl/dspc++?
For example, if the fig_8_7 example code is rearranged as shown below, it will immediately execute the parallel_for operation that waits on e1 and e2.  Is there a way to initialize e1 and e2 as non-signaled in this case?

![fig_8_7_modified](https://user-images.githubusercontent.com/1499591/124876286-74555980-df8f-11eb-8e3b-33910d9a0781.png)

**Comment by jbrodman** [comment]
The parallel for that returns e3 is evaluated immediately, so it uses the values of e1 and e2 as they are at that point in program execution.

Events need to be properly used in program order.

**Comment by jbrodman** [comment]
If you feel that this is a useful case, I would file an issue with the SYCL spec on Khronos's github.

**Comment by mkinsner** [comment]
I've opened https://github.com/KhronosGroup/SYCL-Docs/issues/360 to track discussion on the Khronos side.

**Comment by mkinsner** [comment]
There is active discussion on the public Khronos issue, so I'm closing this issue to avoid duplication.  Thanks for raising this!
