### ISSUE TITLE
fig_6_8_prefetch_memadvise, prefetch doesn't improve performance

### ISSUE THREAD

**Issue by jnorwood** [Apress/data-parallel-CPP#22]
I added measurements of fig_6_8_prefetch_memadvise and noticed that the prefetch didn't improve the performance.
So, I created a simplified test of using the prefetch vs a simple read access of the first position in each block.  The read access, of course, does apparently prefetch the memory so that subsequent use of it is faster.  The prefetch, from all attempts I tried, has no effect.  Below shows modified example results. 
setup-time is time to do read access for the start of each block.
pfsetup-time is time to do prefetch hints for the start of each block.
time is time to do accesses following the initial setup-time accesses
pftime is time to do accesses following the  prefetch hints
note that the first "time" value is low, but the first pftime value does not look improved.
after first time and pftime, all timings are about the same, as expected.

![fig_6_8_prefetch_measure](https://user-images.githubusercontent.com/1499591/127390583-3e7a464d-22d1-441f-941e-debd3f389cb7.png)

I'm testing on NUC Skull Canyon box, building with debug enabled and -O0 optimization.
root@4578405bdff6:/workspaces/data-parallel-CPP-main/build# dpcpp --version
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)
root@4578405bdff6:/workspaces/data-parallel-CPP-main/build# sycl-ls
0. ACC : Intel(R) FPGA Emulation Platform for OpenCL(TM) 1.2 [2021.12.6.0.19_160000]
1. CPU : Intel(R) OpenCL 2.1 [2021.12.6.0.19_160000]
2. GPU : Intel(R) OpenCL HD Graphics 3.0 [21.23.20043]
3. GPU : Intel(R) Level-Zero 1.1 [1.1.20043]
4. HOST: SYCL host platform 1.2 [1.2]

I'm attaching the test program I created to test prefetch, which is a modified fig_6_8 example, built with cmake in Ubuntu 20.04

[fig_6_8_prefetch_memadvise_test.zip](https://github.com/Apress/data-parallel-CPP/files/6896287/fig_6_8_prefetch_memadvise_test.zip)

**Comment by mkinsner** [comment]
Thanks for filing this.  Since prefetch is a hint and has implementation defined (not SYCL-defined) behavior, I don't think it's a problem that no performance change was measured.  Specifically, from the SYCL 2020 specification:

> This operation is an implementation-defined optimization

> Performance hints for shared allocations may be specified by the user by enqueueing prefetch operations on a device. These operations inform the SYCL runtime that the specified shared allocation is likely to be accessed on the device in the future, and that it is free to migrate the allocation to the device.

Depending on the device and implementation decisions, this hint may or may not create measurable performance improvements.

You should probably expect to see more measurable performance gains as implementations mature, but impact will still depend on device and possibly internal heuristics.
