### ISSUE TITLE
Figure 9-14 template parameter "T" not explained in the book

### ISSUE THREAD

**Issue by PiotrFusik** [Apress/data-parallel-CPP#24]
The listing https://github.com/Apress/data-parallel-CPP/blob/63e9eceb909a857705ec7acdbff2559114a7aa0b/samples/Ch09_work_item_communication/fig_9_14_ndrange_sub_group_matmul.cpp defines the template parameter `T` outside of the book snip. This causes confusion to the book reader who is unaware what is `T`.

**Comment by mkinsner** [comment]
Thanks for the issue.  We've updated the book text for the (still unpublished) second edition, and also added commenting in the regions of code that are replicated in the book.
