### ISSUE TITLE
Typos on p. 74 in reference to Fig. 3-6

### ISSUE THREAD

**Issue by vinmierlak** [Apress/data-parallel-CPP#26]
On p. 74, there are two instances of `myAccessor` which, I presume, should be `my_accessor` (as seen in the source code in Fig. 3-6).

**Comment by mkinsner** [comment]
Thanks.  I've confirmed that this is fixed in the (currently unpublished) next edition of the book.

**Comment by vinmierlak** [comment]
Glad to be of assistance.  Good luck with the new edition!
