### ISSUE TITLE
Default build not finding dpcpp

### ISSUE THREAD

**Issue by lfield** [Apress/data-parallel-CPP#3]
On Ubuntu 20.04 (LTS) with Intel oneAPI beta10 the CMake build fails. 

```
c++: error: unrecognized command line option ‘-fsycl’
c++: error: unrecognized command line option ‘-fsycl-unnamed-lambda’
c++: error: unrecognized command line option ‘-ferror-limit=1’
```
Commands used
```
git clone https://github.com/Apress/data-parallel-CPP.git
cd data-parallel-CPP
source /opt/intel/oneapi/setvars.sh
cmake -B  build
cmake --build build
```
Note that on the system /usr/bin/c++ links to /usr/bin/g++ via /etc/alternatives/c++

It looks like dpcpp is not being used.

**Comment by lfield** [comment]
I see from the readme that the following option should have been used. 
```
 -DCMAKE_TOOLCHAIN_FILE=dpcpp_toolchain.cmake 
```
it also works with
```
 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=dpcpp
```

**Comment by mkinsner** [comment]
@lfield do you agree that it's safe to close this issue without any action?
